project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/
  title: "Das IQB auf GitHub - Metadaten"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/iqb-vocabs.github.io
  repo-actions: [issue]

  navbar:
    pinned: true
    search: true
    logo: IQB-klein.png
    right:
      - icon: github
        href: https://github.com/iqb-vocabs/iqb-vocabs.github.io
        aria-label: Source Code

  page-footer:
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - text: Start
        href: index.qmd    
        
  sidebar:
    style: "docked"
    lang: de
    collapse-level: 1
    contents: 
    - href: index.qmd
      text: Start
    - section: "Einführung"
      contents:
        - href: intro/index.qmd
          text: Überblick
        - href: intro/skohub.qmd
          text: "Skohub"
    - section: "Metadatenprofile"
      contents:
        - href: metadatenprofile/index.qmd
          text:  "Überblick"
        - href: metadatenprofile/profile.qmd
          text: "Metadatenprofile"
    - section: "Vokabulare"
      contents:
        - href: vokabulare/index.qmd
          text:  "Überblick"
        - href: vokabulare/bildungstandards.qmd
          text: "Bildungstandards"
        - href: vokabulare/allg_vocabs.qmd
          text: "Aufgaben und Items"
        - href: vokabulare/forschungsdaten.qmd
          text: "Forschungsdaten"
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


