project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/
  title: "IQB Metadaten"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/iqb-vocabs.github.io
  repo-actions: [issue]

  navbar:
    pinned: true
    search: true
    logo: iqb-logo-red.png
    right:
      - icon: github
        href: https://github.com/iqb-vocabs/iqb-vocabs.github.io
        aria-label: Source Code

  page-footer:
    background: light
    right:
      - text: "{{< var iqb.footer >}}"
        href: https://www.iqb.hu-berlin.de
    left:
      - text: "{{< fa house >}}"
        href: index.qmd    
        
  sidebar:
    style: "docked"
    lang: de
    collapse-level: 1
    contents: 
    - href: index.qmd
      text: Start
    - text: "Metadatenprofile"
      href: metadatenprofile/index.qmd
    - section: "Vokabulare"
      href: vokabulare/index.qmd
      contents:
        - href: vokabulare/bildungstandards.qmd
          text: "Bildungstandards"
        - href: vokabulare/allg_vocabs.qmd
          text: "Aufgaben und Items"
        - href: vokabulare/forschungsdaten.qmd
          text: "Forschungsdaten"
    - section: "Spezifikationen"
      href: specs/index.qmd
      contents:
        - specs/metadata-values.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true

